export const SIGN_IN  = 'Log In';
export const EMAIL = 'User';
export const PASSWORD = 'Password';
export const BACK = 'Back';
export const IN = 'Go!';
export const BAD_RESPONSE = 'Response Server Error';
export const WRONG_CREDENTIALS = 'Wrong Credentials';
export const NOT_CREDENTIALS = 'Log with your User and Password';
export const LOGGED ='Succesffully Log In';